version: 0.2
phases:
 install:
   commands:
     - echo "install step"
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - npm build
 post_build:
   commands:
     - aws s3 sync --delete ./dist "s3://www.saxsetups.com"